### ISSUE TITLE
April 8th macOS update seems to have broken pycups.

### ISSUE THREAD

**Issue by hickeroar** [OpenPrinting/pycups#20] opened 2020-04-14 15:54 UTC
https://support.apple.com/en-us/HT201222
https://support.apple.com/en-us/HT211100

Steps to reproduce:

- `python -m venv venv`
- `source venv/bin/activate`
- `pip install pycups`
- `python -c "import cups"`

From here I've seen two exceptions, depending on the version of python I'm using (3.7 in my venv, or 3.6 in a production environment):

3.7:
> ImportError: dlopen([snip]venv/lib/python3.7/site-packages/cups.cpython-37m-darwin.so, 2): Symbol not found: _kSecClass
>   Referenced from: [snip]venv/lib/python3.7/site-packages/cups.cpython-37m-darwin.so
>   Expected in: flat namespace

3.6:
> ImportError: dlopen([snip]lib/python3.6/cups.cpython-36m-darwin.so, 2): Symbol not found: _cupsAdminCreateWindowsPPD
>   Referenced from: [snip]lib/python3.6/cups.cpython-36m-darwin.so
>   Expected in: flat namespace

**Comment by zdohnal** [comment] 2020-04-15 04:58
Hi @hickeroar ,
unfortunately I don't have any MacOS system to reproduce it and your steps work fine in Fedora.
I searched about the errors in google and it seems to be connected to how pycups is compiled in pip (at least that's how I understand pip works - PyPI has only source files and pip runs compilation and installation depending on platform where pip was called...) and how compiled is CUPS and whatever library provides _kSeCClass.
Please try to seek help in Apple support - they will know better how to debug the issue and please let me know if there will need to be any changes in pycups.

**Comment by zdohnal** [comment] 2020-04-15 04:59
I'll close the issue for now, please reopen after Apple investigation and it will need a change in pycups.

**Closed by zdohnal** 2020-04-15 04:59 UTC
