### ISSUE TITLE
No "Connection" Method

### ISSUE THREAD

**Issue by RYoder97** [OpenPrinting/pycups#21] opened 2020-04-17 05:46 UTC
Followed instructions from ReadMe. Tried using the connection method and Python said it didn't have that method. So I inspected the module with the following code:

`#!/usr/local/bin/python3

import os
import cups

print(dir(cups))
`

The only thing that 'cups' has are 
`['CupsGenerator', 'List', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'random', 'string']
`

Any reason why this is?

**Comment by zdohnal** [comment] 2020-04-17 06:49
Hi @RYoder97,

I'm unable to reproduce.

Would you mind telling me what distro you use, how did you download the source and how you invoked python3?
I'm curious about the shebang... why is there invoking python3 from /usr/local? Why don't use system python3? Do you compile the latest python3 source or your OS does not provide python3 at all?

Thank you!

**Comment by zdohnal** [comment] 2020-06-22 05:35
No update for 2 months. Closing.

**Closed by zdohnal** 2020-06-22 05:35 UTC

**Comment by bengartner** [comment] 2020-08-25 02:17
FYI, I saw the same thing, it was because I'd installed a different cups package. Try
`pip uninstall cups`
`pip install pycups`
